name: "pr"

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  get-php-info:
    name: "Get PHP Info"
    runs-on: ubuntu-latest
    outputs:
      extensions: ${{ steps.php-info-matrix.outputs.extensions }}
      versions: ${{ steps.php-info-matrix.outputs.version }}
      lowest-version: ${{ steps.php-info-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@v3
      - id: php-info-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1


  lint:
    needs:
      - get-php-info
    name: "Static Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ fromJson(needs.get-php-info.outputs.lowest-version) }}
          extensions: ${{ join(fromJson(needs.get-php-info.outputs.extensions), ',') }}
      - name: "Composer: Validate composer.json and composer.lock"
        run: composer validate --strict
      - name: "Composer: Install dependencies"
        run: composer install --no-progress --no-interaction
      - name: "Validate Code Styling"
        run: composer aternus:style


  test:
    needs:
      - get-php-info
    name: "Test"
    uses: "./.github/workflows/shared-test.yml"
    with:
      operating-systems: '["ubuntu-latest"]'
      php-versions: ${{ needs.get-php-info.outputs.versions }}
      php-extensions: ${{ needs.get-php-info.outputs.extensions }}
    secrets:
      geonames-username: ${{ secrets.GEONAMES_USERNAME }}
