name: "lint"

on:
  workflow_call:
    inputs:
      operating-system:
        type: string
        required: true
        description: "Operating system"
      php-version:
        type: string
        required: true
        description: "PHP version"
      php-extensions:
        type: string
        required: true
        description: "JSON array of PHP extensions"

jobs:
  code-styling:
    name: "Code Styling"
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ join(fromJson(inputs.php-extensions), ',') }}
      - name: "Composer: Validate composer.json and composer.lock"
        run: composer validate --strict
      - name: "Composer: Install dependencies"
        run: composer install --no-progress --no-interaction
      - name: "Validate Code Styling"
        run: composer aternus:style
