name: "version"

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  get-php-info:
    name: "Get PHP Info"
    runs-on: ubuntu-latest
    outputs:
      extensions: ${{ steps.php-info-matrix.outputs.extensions }}
      versions: ${{ steps.php-info-matrix.outputs.version }}
      lowest-version: ${{ steps.php-info-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@v3
      - id: php-info-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1

  lint:
    needs:
      - get-php-info
    name: "Lint"
    uses: "./.github/workflows/shared-lint.yml"
    with:
      operating-system: ubuntu-latest
      php-version: ${{ needs.get-php-info.outputs.lowest-version }}
      php-extensions: ${{ needs.get-php-info.outputs.extensions }}


  test:
    needs:
      - get-php-info
      - lint
    name: "Test"
    uses: "./.github/workflows/shared-test.yml"
    with:
      operating-systems: '["ubuntu-latest"]'
      php-versions: ${{ needs.get-php-info.outputs.versions }}
      php-extensions: ${{ needs.get-php-info.outputs.extensions }}
    secrets:
      geonames-username: ${{ secrets.GEONAMES_USERNAME }}
